name: go2rtc

x-base-service: &base-service
  restart: unless-stopped
  networks:
    - services
  # network_mode: "host"
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

  tty: true

services:
  go2rtc:
    <<: *base-service
    image: gogo:v1.0.0
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: go2rtc
    ports:
      - "1984:1984"
      - "8554:8554"
      - "8555:8555"
    restart: unless-stopped
    working_dir: /config
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - .test_config:/config
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu, video, display]

networks:
  services:
    external: true